/* Generated By:JavaCC: Do not edit this line. Delang1Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
package delang;
public interface Delang1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int OR = 6;
  /** RegularExpression Id. */
  int NOT = 7;
  /** RegularExpression Id. */
  int SELECT = 8;
  /** RegularExpression Id. */
  int DELETE = 9;
  /** RegularExpression Id. */
  int SAVE = 10;
  /** RegularExpression Id. */
  int SAVEAS = 11;
  /** RegularExpression Id. */
  int CREATE = 12;
  /** RegularExpression Id. */
  int FUNCTION = 13;
  /** RegularExpression Id. */
  int FROM = 14;
  /** RegularExpression Id. */
  int TO = 15;
  /** RegularExpression Id. */
  int AS = 16;
  /** RegularExpression Id. */
  int ROTATE = 17;
  /** RegularExpression Id. */
  int RESIZE = 18;
  /** RegularExpression Id. */
  int CROP = 19;
  /** RegularExpression Id. */
  int BLUR = 20;
  /** RegularExpression Id. */
  int BILATERAL = 21;
  /** RegularExpression Id. */
  int SHARPENING = 22;
  /** RegularExpression Id. */
  int MOSAIC = 23;
  /** RegularExpression Id. */
  int FORMAT = 24;
  /** RegularExpression Id. */
  int LOGTRANSFORMATION = 25;
  /** RegularExpression Id. */
  int INSERTTEXT = 26;
  /** RegularExpression Id. */
  int MERGE = 27;
  /** RegularExpression Id. */
  int BINARY = 28;
  /** RegularExpression Id. */
  int GRAYSCALE = 29;
  /** RegularExpression Id. */
  int SATURATION = 30;
  /** RegularExpression Id. */
  int SEPIA = 31;
  /** RegularExpression Id. */
  int CONSTANT = 32;
  /** RegularExpression Id. */
  int DIGIT = 33;
  /** RegularExpression Id. */
  int ID = 34;
  /** RegularExpression Id. */
  int FILENAME = 35;
  /** RegularExpression Id. */
  int PATH = 36;
  /** RegularExpression Id. */
  int IMGSIZE = 37;
  /** RegularExpression Id. */
  int LINE_COMMENT = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<SELECT>",
    "<DELETE>",
    "<SAVE>",
    "<SAVEAS>",
    "<CREATE>",
    "<FUNCTION>",
    "<FROM>",
    "<TO>",
    "<AS>",
    "\"rotate\"",
    "\"resize\"",
    "\"crop\"",
    "\"blur\"",
    "\"bilateral\"",
    "\"sharpening\"",
    "\"mosaic\"",
    "\"format\"",
    "\"log_transformation\"",
    "\"insert_text\"",
    "\"merge\"",
    "\"binary\"",
    "\"grayscale\"",
    "\"saturation\"",
    "\"sepia\"",
    "<CONSTANT>",
    "<DIGIT>",
    "<ID>",
    "<FILENAME>",
    "<PATH>",
    "<IMGSIZE>",
    "<LINE_COMMENT>",
    "\",\"",
    "\";\"",
  };

}
